### ISSUE TITLE
Suppress `instantiate` output in demo.ipynb

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim.jl#45]
The docs are now built automatically, but unfortunately `instantiate` https://deltares.github.io/Ribasim.jl/demo.html produces a lot of noise.
Any idea how to suppress this @visr or @evetion?

**Comment by visr** [comment]
`Pkg.instantiate(; io=devnull)` should work

https://pkgdocs.julialang.org/v1/api/#Pkg.instantiate

I see that `GLMakie` gives an error in the docs. This package needs a GPU. We could simply take it out of the `run` environment, or perhaps it is better to add a `docs` environment that has only the packages needed for the docs. Because GLMakie is not used in the demo notebook, but CairoMakie is.

**Comment by Hofer-Julian** [comment]
> `Pkg.instantiate(; io=devnull)` should work

👍🏻 

> perhaps it is better to add a `docs` environment that has only the packages needed for the docs

I was a bit hesitant to add a `docs` environment, because that means yet another environment to maintain, but maybe it's indeed the best option.
