### ISSUE TITLE
Cannot build ribasim_cli

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim.jl#61]
After activating the environment in `compile\ribasim_cli\create_app` and running `include("create_app.jl")` I get the following error

```
ERROR: LoadError: ArgumentError: Package Ribasim does not have Legolas in its dependencies:
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have Ribasim checked out for development and have
  added Legolas as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Ribasim
```

**Comment by visr** [comment]
The second bullet applies here. Since the dependencies of Ribasim changes, all the Manifests that have added Ribasim as a dev dependency need to be re-resolved. So running `pkg> resolve` will update these deps just like was done here: https://github.com/Deltares/Ribasim.jl/pull/60/commits/9ccb1c329d68b055cc08b3dbf93a7aee0d23623c#diff-02187f1070d86daf37dadd3e400c0ac5cf876e3cea2ab44e4717757c2f358b1aR1040

**Comment by Hofer-Julian** [comment]
I've tried that, but maybe at the wrong spot :)

How about we have a look together tomorrow or on Friday?
